### ISSUE TITLE
transaction.go:6:5: undefined: conn

### ISSUE THREAD

**Issue by naimsulejmani** [marcboeker/go-duckdb#199]
Hi All,

I am new to duckdb, and started testing in Windows and also on Ubuntu environment  it doesn't open a connection and shows 

```bash
github.com/marcboeker/go-duckdb
../../../../../go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.2/transaction.go:6:5: undefined: conn

```

Code examples that fails to run:

```go
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/marcboeker/go-duckdb"
)

func main() {
	db, _ := sql.Open("duckdb", "")

	db.Exec(`CREATE TABLE person (id INTEGER, name VARCHAR)`)
	db.Exec(`INSERT INTO person VALUES (42, 'John')`)

	var (
		id   int
		name string
	)
	row := db.QueryRow(`SELECT id, name FROM person`)
	_ = row.Scan(&id, &name)
	fmt.Println("id:", id, "name:", name)
}

```

Any help regarding this!?

**Comment by marcboeker** [comment]
> However, at least for this issue, I receive the same error on MacOS 14.4.1 Arm:
> github.com/marcboeker/go-duckdb@v1.6.1/transaction.go:6:5: undefined: conn

@element-of-surprise That's weird. I've tested it with 1.6.2 just now and it works on a M3 with 14.4.1. Could you please manually check out the go-duckdb repo and run `make test` and `make examples`? This should work too. Otherwise please post the error message you receive.

**Comment by mixam85** [comment]
Hello, I have the similar issue in Debian 11 docker, but not on my Arch Linux.
```
# github.com/marcboeker/go-duckdb
/root/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.1/transaction.go:6:5: undefined: conn
```

**Comment by mixam85** [comment]
Installing `build-essential` and running `make` and `make test` in `/root/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.1/` folder fixed it for me.

**Comment by hjlp20150803** [comment]
../../../pkg/mod/github.com/marcboeker/go-duckdb@v1.6.3/transaction.go:6:5: undefined: conn

**Comment by alvaradojl** [comment]
> I get the same error when building in WSL 2 Ubuntu 22.04

oh I actually had forgotten to set CGO_ENABLED=1 as instructed in the README, once I changed this, the build worked

**Comment by arbourd** [comment]
> oh I actually had forgotten to set CGO_ENABLED=1 as instructed in the README, once I changed this, the build worked

Yup! I think this can be closed. `CGO_ENABLED=1` must be enabled when using this.
